# Generated by Django 5.2.12 on 2026-03-07 16:55

import shared.constants.document
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocumentStateMachineDef",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("document_type", models.CharField(max_length=80)),
                (
                    "from_state",
                    models.CharField(
                        choices=[
                            (
                                shared.constants.document.DOC_STATUS["DRAFT"],
                                shared.constants.document.DOC_STATUS["DRAFT"],
                            ),
                            (
                                shared.constants.document.DOC_STATUS["SUBMITTED"],
                                shared.constants.document.DOC_STATUS["SUBMITTED"],
                            ),
                            (
                                shared.constants.document.DOC_STATUS["CONFIRMED"],
                                shared.constants.document.DOC_STATUS["CONFIRMED"],
                            ),
                            (
                                shared.constants.document.DOC_STATUS["COMPLETED"],
                                shared.constants.document.DOC_STATUS["COMPLETED"],
                            ),
                            (
                                shared.constants.document.DOC_STATUS["CANCELLED"],
                                shared.constants.document.DOC_STATUS["CANCELLED"],
                            ),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "to_state",
                    models.CharField(
                        choices=[
                            (
                                shared.constants.document.DOC_STATUS["DRAFT"],
                                shared.constants.document.DOC_STATUS["DRAFT"],
                            ),
                            (
                                shared.constants.document.DOC_STATUS["SUBMITTED"],
                                shared.constants.document.DOC_STATUS["SUBMITTED"],
                            ),
                            (
                                shared.constants.document.DOC_STATUS["CONFIRMED"],
                                shared.constants.document.DOC_STATUS["CONFIRMED"],
                            ),
                            (
                                shared.constants.document.DOC_STATUS["COMPLETED"],
                                shared.constants.document.DOC_STATUS["COMPLETED"],
                            ),
                            (
                                shared.constants.document.DOC_STATUS["CANCELLED"],
                                shared.constants.document.DOC_STATUS["CANCELLED"],
                            ),
                        ],
                        max_length=20,
                    ),
                ),
                ("permission_code", models.CharField(blank=True, max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "document_state_machine_def",
                "unique_together": {("document_type", "from_state", "to_state")},
            },
        ),
        migrations.CreateModel(
            name="DocumentTransitionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_id", models.UUIDField(db_index=True)),
                ("document_type", models.CharField(max_length=80)),
                ("document_id", models.UUIDField()),
                ("from_state", models.CharField(max_length=20)),
                ("to_state", models.CharField(max_length=20)),
                ("operator_id", models.UUIDField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "document_transition_log",
                "indexes": [
                    models.Index(
                        fields=["company_id", "document_type", "document_id"],
                        name="document_tr_company_6bdb7c_idx",
                    )
                ],
            },
        ),
    ]
