# Generated by Django 5.2.12 on 2026-03-10 17:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        ("material", "0002_material_constraints"),
    ]

    operations = [
        migrations.CreateModel(
            name="IoTDevice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("device_code", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=120)),
                ("type", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("maintenance", "Maintenance"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "prd_iot_device",
            },
        ),
        migrations.CreateModel(
            name="ProductionPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("plan_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("planned", "Planned"),
                            ("approved", "Approved"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("capacity_json", models.JSONField(blank=True, default=dict)),
                ("mrp_result_json", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "prd_production_plan",
            },
        ),
        migrations.CreateModel(
            name="BOM",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("retired", "Retired"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "product_material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_boms",
                        to="material.material",
                    ),
                ),
            ],
            options={
                "db_table": "prd_bom",
                "unique_together": {("company_id", "product_material", "version")},
            },
        ),
        migrations.CreateModel(
            name="BOMLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("qty_per_unit", models.DecimalField(decimal_places=6, max_digits=20)),
                (
                    "scrap_rate",
                    models.DecimalField(decimal_places=4, default=0, max_digits=8),
                ),
                (
                    "bom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="production.bom",
                    ),
                ),
                (
                    "component_bom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="used_as_subassembly_lines",
                        to="production.bom",
                    ),
                ),
                (
                    "component_material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bom_component_lines",
                        to="material.material",
                    ),
                ),
            ],
            options={
                "db_table": "prd_bom_line",
            },
        ),
        migrations.CreateModel(
            name="IoTMetric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("metric_key", models.CharField(max_length=64)),
                ("value", models.DecimalField(decimal_places=6, max_digits=20)),
                ("recorded_at", models.DateTimeField()),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="production.iotdevice",
                    ),
                ),
            ],
            options={
                "db_table": "prd_iot_metric",
            },
        ),
        migrations.CreateModel(
            name="ManufacturingOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("doc_no", models.CharField(max_length=64)),
                ("planned_qty", models.DecimalField(decimal_places=6, max_digits=20)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "progress_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("released", "Released"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "product_material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="manufacturing_orders",
                        to="material.material",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="manufacturing_orders",
                        to="material.warehouse",
                    ),
                ),
            ],
            options={
                "db_table": "prd_manufacturing_order",
                "unique_together": {("company_id", "doc_no")},
            },
        ),
        migrations.AddField(
            model_name="iotdevice",
            name="bound_mo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="iot_devices",
                to="production.manufacturingorder",
            ),
        ),
        migrations.CreateModel(
            name="MOIssueLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("required_qty", models.DecimalField(decimal_places=6, max_digits=20)),
                (
                    "issued_qty",
                    models.DecimalField(decimal_places=6, default=0, max_digits=20),
                ),
                (
                    "component_material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mo_issue_lines",
                        to="material.material",
                    ),
                ),
                (
                    "mo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issue_lines",
                        to="production.manufacturingorder",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mo_issue_lines",
                        to="inventory.reservation",
                    ),
                ),
            ],
            options={
                "db_table": "prd_mo_issue_line",
            },
        ),
        migrations.CreateModel(
            name="MOReceiptLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("received_qty", models.DecimalField(decimal_places=6, max_digits=20)),
                (
                    "lot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mo_receipt_lines",
                        to="inventory.lot",
                    ),
                ),
                (
                    "mo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipt_lines",
                        to="production.manufacturingorder",
                    ),
                ),
                (
                    "product_material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mo_receipt_lines",
                        to="material.material",
                    ),
                ),
            ],
            options={
                "db_table": "prd_mo_receipt_line",
            },
        ),
        migrations.CreateModel(
            name="ProductionQC",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "stage",
                    models.CharField(
                        choices=[("ipqc", "IPQC"), ("fqc", "FQC")], max_length=16
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[("pass", "Pass"), ("fail", "Fail"), ("hold", "Hold")],
                        max_length=16,
                    ),
                ),
                ("inspector_id", models.UUIDField()),
                ("notes", models.TextField(blank=True)),
                ("measurements_json", models.JSONField(blank=True, default=dict)),
                (
                    "mo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qc_records",
                        to="production.manufacturingorder",
                    ),
                ),
            ],
            options={
                "db_table": "prd_production_qc",
            },
        ),
        migrations.AlterUniqueTogether(
            name="iotdevice",
            unique_together={("company_id", "device_code")},
        ),
    ]
