# Generated by Django 5.2.12 on 2026-03-10 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0001_initial"),
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="manufacturingorder",
            name="production_mode",
            field=models.CharField(
                choices=[("mts", "Make To Stock"), ("mto", "Make To Order")],
                default="mts",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="manufacturingorder",
            name="sales_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="manufacturing_orders",
                to="sales.salesorder",
            ),
        ),
    ]
