# Generated by Django 5.2.12 on 2026-03-10 18:17

import shared.constants.document
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0002_manufacturingorder_production_mode_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manufacturingorder",
            name="status",
            field=models.CharField(
                choices=[
                    (
                        shared.constants.document.DOC_STATUS["DRAFT"],
                        shared.constants.document.DOC_STATUS["DRAFT"],
                    ),
                    (
                        shared.constants.document.DOC_STATUS["SUBMITTED"],
                        shared.constants.document.DOC_STATUS["SUBMITTED"],
                    ),
                    (
                        shared.constants.document.DOC_STATUS["CONFIRMED"],
                        shared.constants.document.DOC_STATUS["CONFIRMED"],
                    ),
                    (
                        shared.constants.document.DOC_STATUS["COMPLETED"],
                        shared.constants.document.DOC_STATUS["COMPLETED"],
                    ),
                    (
                        shared.constants.document.DOC_STATUS["CANCELLED"],
                        shared.constants.document.DOC_STATUS["CANCELLED"],
                    ),
                ],
                default=shared.constants.document.DOC_STATUS["DRAFT"],
                max_length=20,
            ),
        ),
    ]
