# Generated by Django 5.2.12 on 2026-03-10 18:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        ("material", "0002_material_constraints"),
        ("production", "0003_alter_manufacturingorder_status"),
        ("purchase", "0002_invoicematch_company_id"),
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountingInvoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "type",
                    models.CharField(
                        choices=[("AR", "AR"), ("AP", "AP")], max_length=8
                    ),
                ),
                ("counterparty_type", models.CharField(max_length=32)),
                ("counterparty_id", models.UUIDField()),
                ("issue_date", models.DateField()),
                ("due_date", models.DateField(blank=True, null=True)),
                ("currency", models.CharField(max_length=8)),
                ("total_amount", models.DecimalField(decimal_places=6, max_digits=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("issued", "Issued"),
                            ("paid", "Paid"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accounting_invoices",
                        to="purchase.purchaseorder",
                    ),
                ),
                (
                    "sales_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accounting_invoices",
                        to="sales.salesorder",
                    ),
                ),
            ],
            options={
                "db_table": "acct_invoice",
            },
        ),
        migrations.CreateModel(
            name="CostLayer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("in_qty", models.DecimalField(decimal_places=6, max_digits=20)),
                ("remaining_qty", models.DecimalField(decimal_places=6, max_digits=20)),
                ("unit_cost", models.DecimalField(decimal_places=6, max_digits=20)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accounting_cost_layers",
                        to="material.material",
                    ),
                ),
                (
                    "source_ledger",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accounting_cost_layer",
                        to="inventory.stockledger",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accounting_cost_layers",
                        to="material.warehouse",
                    ),
                ),
            ],
            options={
                "db_table": "acct_cost_layer",
            },
        ),
        migrations.CreateModel(
            name="FinancialReportSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("period", models.CharField(max_length=32)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("BS", "Balance Sheet"),
                            ("PL", "Profit and Loss"),
                            ("CF", "Cash Flow"),
                        ],
                        max_length=8,
                    ),
                ),
                ("payload_json", models.JSONField(blank=True, default=dict)),
                (
                    "generated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "db_table": "acct_financial_report_snapshot",
                "unique_together": {("company_id", "period", "report_type")},
            },
        ),
        migrations.CreateModel(
            name="FixedAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("asset_code", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=255)),
                ("purchase_date", models.DateField()),
                ("purchase_cost", models.DecimalField(decimal_places=6, max_digits=20)),
                ("depreciation_method", models.CharField(max_length=32)),
                ("useful_life_months", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("disposed", "Disposed")],
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "source_purchase_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fixed_assets",
                        to="purchase.purchaseorder",
                    ),
                ),
            ],
            options={
                "db_table": "acct_fixed_asset",
                "unique_together": {("company_id", "asset_code")},
            },
        ),
        migrations.CreateModel(
            name="AssetMaintenance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("date", models.DateField()),
                ("content", models.TextField()),
                ("cost", models.DecimalField(decimal_places=6, max_digits=20)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenances",
                        to="accounting.fixedasset",
                    ),
                ),
            ],
            options={
                "db_table": "acct_asset_maintenance",
            },
        ),
        migrations.CreateModel(
            name="AccountingPosting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "entry_type",
                    models.CharField(choices=[("invoice", "Invoice")], max_length=20),
                ),
                ("source_doc_type", models.CharField(max_length=64)),
                ("source_doc_id", models.UUIDField()),
                (
                    "status",
                    models.CharField(
                        choices=[("posted", "Posted"), ("reversed", "Reversed")],
                        default="posted",
                        max_length=20,
                    ),
                ),
                ("posted_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("reversed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="postings",
                        to="accounting.accountinginvoice",
                    ),
                ),
                (
                    "source_production_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accounting_postings",
                        to="production.manufacturingorder",
                    ),
                ),
            ],
            options={
                "db_table": "acct_posting",
                "unique_together": {
                    ("company_id", "entry_type", "source_doc_type", "source_doc_id")
                },
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "direction",
                    models.CharField(
                        choices=[("in", "In"), ("out", "Out")], max_length=8
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=6, max_digits=20)),
                ("currency", models.CharField(max_length=8)),
                ("paid_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("method", models.CharField(blank=True, max_length=32)),
                ("reference", models.CharField(blank=True, max_length=120)),
                ("source_ref_type", models.CharField(blank=True, max_length=64)),
                ("source_ref_id", models.UUIDField(blank=True, null=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="accounting.accountinginvoice",
                    ),
                ),
            ],
            options={
                "db_table": "acct_payment",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            models.Q(("source_ref_type", ""), _negated=True),
                            ("source_ref_id__isnull", False),
                        ),
                        fields=("company_id", "source_ref_type", "source_ref_id"),
                        name="uniq_acct_payment_source_ref",
                    )
                ],
            },
        ),
    ]
