# Generated by Django 5.2.12 on 2026-03-11 16:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0002_delete_costlayer"),
        ("material", "0002_material_constraints"),
    ]

    operations = [
        migrations.CreateModel(
            name="PeriodProductCost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("period", models.CharField(max_length=7)),
                ("currency", models.CharField(max_length=8)),
                (
                    "total_in_qty",
                    models.DecimalField(decimal_places=6, default=0, max_digits=20),
                ),
                (
                    "total_in_cost",
                    models.DecimalField(decimal_places=6, default=0, max_digits=20),
                ),
                (
                    "ending_qty",
                    models.DecimalField(decimal_places=6, default=0, max_digits=20),
                ),
                (
                    "ending_cost",
                    models.DecimalField(decimal_places=6, default=0, max_digits=20),
                ),
                ("layer_count", models.IntegerField(default=0)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="period_product_costs",
                        to="material.material",
                    ),
                ),
            ],
            options={
                "db_table": "acct_period_product_cost",
                "unique_together": {("company_id", "period", "material")},
            },
        ),
    ]
