# Generated by Django 5.2.12 on 2026-03-09 17:05

import shared.constants.document
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0002_transportorder_sales_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="containerrecoveryplan",
            name="status",
            field=models.CharField(
                choices=[
                    (
                        shared.constants.document.DOC_STATUS["DRAFT"],
                        shared.constants.document.DOC_STATUS["DRAFT"],
                    ),
                    (
                        shared.constants.document.DOC_STATUS["SUBMITTED"],
                        shared.constants.document.DOC_STATUS["SUBMITTED"],
                    ),
                    (
                        shared.constants.document.DOC_STATUS["CONFIRMED"],
                        shared.constants.document.DOC_STATUS["CONFIRMED"],
                    ),
                    (
                        shared.constants.document.DOC_STATUS["COMPLETED"],
                        shared.constants.document.DOC_STATUS["COMPLETED"],
                    ),
                    (
                        shared.constants.document.DOC_STATUS["CANCELLED"],
                        shared.constants.document.DOC_STATUS["CANCELLED"],
                    ),
                ],
                default=shared.constants.document.DOC_STATUS["DRAFT"],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transportorder",
            name="status",
            field=models.CharField(
                choices=[
                    (
                        shared.constants.document.DOC_STATUS["DRAFT"],
                        shared.constants.document.DOC_STATUS["DRAFT"],
                    ),
                    (
                        shared.constants.document.DOC_STATUS["SUBMITTED"],
                        shared.constants.document.DOC_STATUS["SUBMITTED"],
                    ),
                    (
                        shared.constants.document.DOC_STATUS["CONFIRMED"],
                        shared.constants.document.DOC_STATUS["CONFIRMED"],
                    ),
                    (
                        shared.constants.document.DOC_STATUS["COMPLETED"],
                        shared.constants.document.DOC_STATUS["COMPLETED"],
                    ),
                    (
                        shared.constants.document.DOC_STATUS["CANCELLED"],
                        shared.constants.document.DOC_STATUS["CANCELLED"],
                    ),
                ],
                default=shared.constants.document.DOC_STATUS["DRAFT"],
                max_length=20,
            ),
        ),
    ]
