# Generated by Django 5.2.12 on 2026-03-10 14:55

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0003_alter_containerrecoveryplan_status_and_more"),
        ("material", "0002_material_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="transportorder",
            name="actual_arrival_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transportorder",
            name="actual_departure_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transportorder",
            name="completion_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="transportorder",
            name="receiver_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="transportorder",
            name="signed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transportorder",
            name="signoff_meta",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="TransportRecoveryLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("qty_actual", models.DecimalField(decimal_places=6, max_digits=20)),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "line_amount",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=20
                    ),
                ),
                ("condition_code", models.CharField(blank=True, max_length=64)),
                ("remark", models.TextField(blank=True)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transport_recovery_lines",
                        to="material.material",
                    ),
                ),
                (
                    "transport_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recovery_lines",
                        to="logistics.transportorder",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transport_recovery_lines",
                        to="material.warehouse",
                    ),
                ),
            ],
            options={
                "db_table": "log_transport_recovery_line",
            },
        ),
    ]
