# Generated by Django 5.2.12 on 2026-03-07 16:55

import django.db.models.deletion
import shared.constants.modules
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rbac", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "company",
            },
        ),
        migrations.CreateModel(
            name="CompanyMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="company.company",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="memberships",
                        to="rbac.role",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "company_membership",
                "unique_together": {("user", "company")},
            },
        ),
        migrations.CreateModel(
            name="CompanyModule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "module_code",
                    models.CharField(
                        choices=[
                            (
                                shared.constants.modules.MODULE_CODES["CORE"],
                                shared.constants.modules.MODULE_CODES["CORE"],
                            ),
                            (
                                shared.constants.modules.MODULE_CODES["COMPANY"],
                                shared.constants.modules.MODULE_CODES["COMPANY"],
                            ),
                            (
                                shared.constants.modules.MODULE_CODES["AUTH"],
                                shared.constants.modules.MODULE_CODES["AUTH"],
                            ),
                            (
                                shared.constants.modules.MODULE_CODES["DOC"],
                                shared.constants.modules.MODULE_CODES["DOC"],
                            ),
                            (
                                shared.constants.modules.MODULE_CODES["AUDIT"],
                                shared.constants.modules.MODULE_CODES["AUDIT"],
                            ),
                            (
                                shared.constants.modules.MODULE_CODES["CONFIG"],
                                shared.constants.modules.MODULE_CODES["CONFIG"],
                            ),
                            (
                                shared.constants.modules.MODULE_CODES["MATERIAL"],
                                shared.constants.modules.MODULE_CODES["MATERIAL"],
                            ),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="company.company",
                    ),
                ),
            ],
            options={
                "db_table": "company_module",
                "unique_together": {("company", "module_code")},
            },
        ),
    ]
