# Generated by Django 5.2.12 on 2026-03-08 10:48

import shared.constants.modules
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_alter_companymodule_module_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companymodule",
            name="module_code",
            field=models.CharField(
                choices=[
                    (
                        shared.constants.modules.MODULE_CODES["CORE"],
                        shared.constants.modules.MODULE_CODES["CORE"],
                    ),
                    (
                        shared.constants.modules.MODULE_CODES["COMPANY"],
                        shared.constants.modules.MODULE_CODES["COMPANY"],
                    ),
                    (
                        shared.constants.modules.MODULE_CODES["AUTH"],
                        shared.constants.modules.MODULE_CODES["AUTH"],
                    ),
                    (
                        shared.constants.modules.MODULE_CODES["DOC"],
                        shared.constants.modules.MODULE_CODES["DOC"],
                    ),
                    (
                        shared.constants.modules.MODULE_CODES["AUDIT"],
                        shared.constants.modules.MODULE_CODES["AUDIT"],
                    ),
                    (
                        shared.constants.modules.MODULE_CODES["CONFIG"],
                        shared.constants.modules.MODULE_CODES["CONFIG"],
                    ),
                    (
                        shared.constants.modules.MODULE_CODES["MATERIAL"],
                        shared.constants.modules.MODULE_CODES["MATERIAL"],
                    ),
                    (
                        shared.constants.modules.MODULE_CODES["INVENTORY"],
                        shared.constants.modules.MODULE_CODES["INVENTORY"],
                    ),
                    (
                        shared.constants.modules.MODULE_CODES["PURCHASE"],
                        shared.constants.modules.MODULE_CODES["PURCHASE"],
                    ),
                ],
                max_length=50,
            ),
        ),
    ]
