# Generated by Django 5.2.12 on 2026-03-08 10:48

import django.db.models.deletion
import shared.constants.document
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        ("material", "0002_material_constraints"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("doc_no", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (
                                shared.constants.document.DOC_STATUS["DRAFT"],
                                shared.constants.document.DOC_STATUS["DRAFT"],
                            ),
                            (
                                shared.constants.document.DOC_STATUS["SUBMITTED"],
                                shared.constants.document.DOC_STATUS["SUBMITTED"],
                            ),
                            (
                                shared.constants.document.DOC_STATUS["CONFIRMED"],
                                shared.constants.document.DOC_STATUS["CONFIRMED"],
                            ),
                            (
                                shared.constants.document.DOC_STATUS["COMPLETED"],
                                shared.constants.document.DOC_STATUS["COMPLETED"],
                            ),
                            (
                                shared.constants.document.DOC_STATUS["CANCELLED"],
                                shared.constants.document.DOC_STATUS["CANCELLED"],
                            ),
                        ],
                        default=shared.constants.document.DOC_STATUS["DRAFT"],
                        max_length=20,
                    ),
                ),
                ("expected_date", models.DateField(blank=True, null=True)),
                ("currency", models.CharField(max_length=8)),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=20
                    ),
                ),
                ("remark", models.TextField(blank=True)),
            ],
            options={
                "db_table": "pur_purchase_order",
            },
        ),
        migrations.CreateModel(
            name="RFQTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("llm_enabled", models.BooleanField(default=False)),
                ("schedule_json", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "pur_rfq_task",
            },
        ),
        migrations.CreateModel(
            name="GoodsReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("doc_no", models.CharField(max_length=64)),
                ("received_date", models.DateField()),
                ("is_partial", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (
                                shared.constants.document.DOC_STATUS["DRAFT"],
                                shared.constants.document.DOC_STATUS["DRAFT"],
                            ),
                            (
                                shared.constants.document.DOC_STATUS["SUBMITTED"],
                                shared.constants.document.DOC_STATUS["SUBMITTED"],
                            ),
                            (
                                shared.constants.document.DOC_STATUS["CONFIRMED"],
                                shared.constants.document.DOC_STATUS["CONFIRMED"],
                            ),
                            (
                                shared.constants.document.DOC_STATUS["COMPLETED"],
                                shared.constants.document.DOC_STATUS["COMPLETED"],
                            ),
                            (
                                shared.constants.document.DOC_STATUS["CANCELLED"],
                                shared.constants.document.DOC_STATUS["CANCELLED"],
                            ),
                        ],
                        default=shared.constants.document.DOC_STATUS["DRAFT"],
                        max_length=20,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goods_receipts",
                        to="material.warehouse",
                    ),
                ),
                (
                    "po",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goods_receipts",
                        to="purchase.purchaseorder",
                    ),
                ),
            ],
            options={
                "db_table": "pur_goods_receipt",
                "unique_together": {("company_id", "doc_no")},
            },
        ),
        migrations.CreateModel(
            name="IQCRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "result",
                    models.CharField(
                        choices=[("pass", "Pass"), ("fail", "Fail"), ("hold", "Hold")],
                        max_length=8,
                    ),
                ),
                ("inspector_id", models.UUIDField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "grn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="iqc_records",
                        to="purchase.goodsreceipt",
                    ),
                ),
            ],
            options={
                "db_table": "pur_iqc_record",
            },
        ),
        migrations.CreateModel(
            name="InvoiceMatch",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("invoice_id", models.UUIDField()),
                (
                    "matched_amount",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=20
                    ),
                ),
                ("rule_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "grn",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice_matches",
                        to="purchase.goodsreceipt",
                    ),
                ),
                (
                    "po",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice_matches",
                        to="purchase.purchaseorder",
                    ),
                ),
            ],
            options={
                "db_table": "pur_invoice_match",
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderLine",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("qty", models.DecimalField(decimal_places=6, max_digits=20)),
                ("price", models.DecimalField(decimal_places=6, max_digits=20)),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=8
                    ),
                ),
                (
                    "suggested_qty",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_order_lines",
                        to="material.material",
                    ),
                ),
                (
                    "po",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="purchase.purchaseorder",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_order_lines",
                        to="material.warehouse",
                    ),
                ),
            ],
            options={
                "db_table": "pur_purchase_order_line",
            },
        ),
        migrations.CreateModel(
            name="GoodsReceiptLine",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("received_qty", models.DecimalField(decimal_places=6, max_digits=20)),
                (
                    "grn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="purchase.goodsreceipt",
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goods_receipt_lines",
                        to="inventory.lot",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goods_receipt_lines",
                        to="material.material",
                    ),
                ),
                (
                    "serial",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goods_receipt_lines",
                        to="inventory.serial",
                    ),
                ),
                (
                    "po_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goods_receipt_lines",
                        to="purchase.purchaseorderline",
                    ),
                ),
            ],
            options={
                "db_table": "pur_goods_receipt_line",
            },
        ),
        migrations.CreateModel(
            name="RFQLine",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("qty", models.DecimalField(decimal_places=6, max_digits=20)),
                ("target_date", models.DateField()),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rfq_lines",
                        to="material.material",
                    ),
                ),
                (
                    "rfq",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="purchase.rfqtask",
                    ),
                ),
            ],
            options={
                "db_table": "pur_rfq_line",
            },
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("code", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=255)),
                ("contact_json", models.JSONField(blank=True, default=dict)),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=3
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "pur_vendor",
                "unique_together": {("company_id", "code")},
            },
        ),
        migrations.CreateModel(
            name="RFQQuote",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("price", models.DecimalField(decimal_places=6, max_digits=20)),
                ("currency", models.CharField(max_length=8)),
                ("lead_time_days", models.IntegerField()),
                ("valid_until", models.DateField()),
                ("source", models.CharField(blank=True, max_length=32)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rfq_quotes",
                        to="material.material",
                    ),
                ),
                (
                    "rfq",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotes",
                        to="purchase.rfqtask",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotes",
                        to="purchase.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "pur_rfq_quote",
            },
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_orders",
                to="purchase.vendor",
            ),
        ),
        migrations.CreateModel(
            name="VendorHistory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("event_type", models.CharField(max_length=64)),
                ("content", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="purchase.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "pur_vendor_history",
            },
        ),
        migrations.AlterUniqueTogether(
            name="purchaseorder",
            unique_together={("company_id", "doc_no")},
        ),
    ]
