from .enum_compat import StrEnum


class PERMISSION_CODES(StrEnum):
    DOC_SUBMIT = "doc.submit"
    DOC_CONFIRM = "doc.confirm"
    DOC_COMPLETE = "doc.complete"
    DOC_CANCEL = "doc.cancel"
    DOC_CANCEL_COMPLETED = "doc.cancel.completed"

    MATERIAL_UOM_CREATE = "material.uom.create"
    MATERIAL_CATEGORY_CREATE = "material.category.create"
    MATERIAL_MATERIAL_CREATE = "material.material.create"
    MATERIAL_WAREHOUSE_CREATE = "material.warehouse.create"
    MATERIAL_WAREHOUSE_ZONE_CREATE = "material.warehouse_zone.create"
    MATERIAL_BIN_LOCATION_CREATE = "material.bin_location.create"
    INVENTORY_STOCK_LEDGER_WRITE = "inventory.stock_ledger.write"
    INVENTORY_RESERVATION_CREATE = "inventory.reservation.create"
    INVENTORY_RESERVATION_RELEASE = "inventory.reservation.release"
    INVENTORY_RESERVATION_CONSUME = "inventory.reservation.consume"
    INVENTORY_TRANSFER_CREATE = "inventory.transfer.create"
    INVENTORY_TRANSFER_SHIP = "inventory.transfer.ship"
    INVENTORY_TRANSFER_RECEIVE = "inventory.transfer.receive"
    INVENTORY_STOCK_COUNT_CREATE = "inventory.stock_count.create"
    INVENTORY_STOCK_COUNT_POST = "inventory.stock_count.post"
    PURCHASE_VENDOR_CREATE = "purchase.vendor.create"
    PURCHASE_RFQ_CREATE = "purchase.rfq.create"
    PURCHASE_ORDER_CREATE = "purchase.order.create"
    PURCHASE_GRN_CREATE = "purchase.grn.create"
    PURCHASE_IQC_CREATE = "purchase.iqc.create"
    PURCHASE_AP_MATCH_CREATE = "purchase.ap_match.create"

    SALES_CUSTOMER_CREATE = "sales.customer.create"
    SALES_PRICING_CREATE = "sales.pricing.create"
    SALES_QUOTE_CREATE = "sales.quote.create"
    SALES_ORDER_CREATE = "sales.order.create"
    SALES_SHIPMENT_CREATE = "sales.shipment.create"
    SALES_RMA_CREATE = "sales.rma.create"

    LOGISTICS_TRANSPORT_ORDER_CREATE = "logistics.transport_order.create"
    LOGISTICS_TRANSPORT_ORDER_UPDATE = "logistics.transport_order.update"
    LOGISTICS_TRANSPORT_ORDER_CANCEL = "logistics.transport_order.cancel"
    LOGISTICS_SHIPMENT_TRACKING_CREATE = "logistics.shipment_tracking.create"
    LOGISTICS_SHIPMENT_TRACKING_UPDATE = "logistics.shipment_tracking.update"
    LOGISTICS_SHIPMENT_TRACKING_CANCEL = "logistics.shipment_tracking.cancel"
    LOGISTICS_CONTAINER_RECOVERY_CREATE = "logistics.container_recovery.create"
    LOGISTICS_CONTAINER_RECOVERY_UPDATE = "logistics.container_recovery.update"
    LOGISTICS_CONTAINER_RECOVERY_CANCEL = "logistics.container_recovery.cancel"
    LOGISTICS_FREIGHT_CHARGE_CREATE = "logistics.freight_charge.create"
    LOGISTICS_FREIGHT_CHARGE_UPDATE = "logistics.freight_charge.update"
    LOGISTICS_FREIGHT_CHARGE_CANCEL = "logistics.freight_charge.cancel"
    LOGISTICS_INSURANCE_POLICY_CREATE = "logistics.insurance_policy.create"
    LOGISTICS_INSURANCE_POLICY_UPDATE = "logistics.insurance_policy.update"
    LOGISTICS_INSURANCE_POLICY_CANCEL = "logistics.insurance_policy.cancel"

    PRODUCTION_BOM_CREATE = "production.bom.create"
    PRODUCTION_MO_CREATE = "production.mo.create"
    PRODUCTION_MO_ISSUE = "production.mo.issue"
    PRODUCTION_MO_RECEIPT = "production.mo.receipt"
    PRODUCTION_MO_TRANSITION = "production.mo.transition"
    PRODUCTION_QC_CREATE = "production.qc.create"
    PRODUCTION_IOT_DEVICE_CREATE = "production.iot_device.create"
    PRODUCTION_IOT_METRIC_CREATE = "production.iot_metric.create"
    PRODUCTION_PLAN_CREATE = "production.plan.create"
    PRODUCTION_PLAN_UPDATE = "production.plan.update"
