# Generated by Django 5.2.12 on 2026-03-07 16:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(max_length=120)),
                ("value", models.JSONField(blank=True, default=dict)),
                (
                    "scope",
                    models.CharField(
                        choices=[("global", "global"), ("company", "company")],
                        default="global",
                        max_length=20,
                    ),
                ),
                ("company_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "system_config",
                "indexes": [
                    models.Index(
                        fields=["scope", "company_id", "key"],
                        name="system_conf_scope_afe95e_idx",
                    )
                ],
                "unique_together": {("key", "scope", "company_id")},
            },
        ),
    ]
