# Generated by Django 5.2.12 on 2026-03-07 16:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("company_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("action", models.CharField(max_length=100)),
                ("resource_type", models.CharField(max_length=100)),
                ("resource_id", models.CharField(max_length=64)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "audit_event",
                "indexes": [
                    models.Index(
                        fields=["company_id", "resource_type", "resource_id"],
                        name="audit_event_company_82b98a_idx",
                    ),
                    models.Index(
                        fields=["actor_id", "timestamp"],
                        name="audit_event_actor_i_b9f2c7_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditFieldDiff",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("field", models.CharField(max_length=120)),
                ("old_value", models.TextField(blank=True)),
                ("new_value", models.TextField(blank=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_diffs",
                        to="audit.auditevent",
                    ),
                ),
            ],
            options={
                "db_table": "audit_field_diff",
            },
        ),
    ]
