# Generated by Django 5.2.12 on 2026-03-08 14:32

import django.db.models.deletion
import shared.constants.document
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        ("material", "0002_material_constraints"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("code", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=255)),
                ("contact_json", models.JSONField(blank=True, default=dict)),
                (
                    "credit_limit",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=20
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "sal_customer",
                "unique_together": {("company_id", "code")},
            },
        ),
        migrations.CreateModel(
            name="CustomerPriceList",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("price", models.DecimalField(decimal_places=6, max_digits=20)),
                ("currency", models.CharField(max_length=8)),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="price_list_entries",
                        to="sales.customer",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_price_list_entries",
                        to="material.material",
                    ),
                ),
            ],
            options={
                "db_table": "sal_customer_price_list",
            },
        ),
        migrations.CreateModel(
            name="PricingRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=120)),
                ("rule_json", models.JSONField(blank=True, default=dict)),
                ("enabled", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "sal_pricing_rule",
                "unique_together": {("company_id", "name")},
            },
        ),
        migrations.CreateModel(
            name="RMA",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("doc_no", models.CharField(max_length=64)),
                ("reason_code", models.CharField(max_length=64)),
                ("reason_text", models.TextField(blank=True)),
                ("quality_issue_flag", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (
                                shared.constants.document.DOC_STATUS["DRAFT"],
                                shared.constants.document.DOC_STATUS["DRAFT"],
                            ),
                            (
                                shared.constants.document.DOC_STATUS["SUBMITTED"],
                                shared.constants.document.DOC_STATUS["SUBMITTED"],
                            ),
                            (
                                shared.constants.document.DOC_STATUS["CONFIRMED"],
                                shared.constants.document.DOC_STATUS["CONFIRMED"],
                            ),
                            (
                                shared.constants.document.DOC_STATUS["COMPLETED"],
                                shared.constants.document.DOC_STATUS["COMPLETED"],
                            ),
                            (
                                shared.constants.document.DOC_STATUS["CANCELLED"],
                                shared.constants.document.DOC_STATUS["CANCELLED"],
                            ),
                        ],
                        default=shared.constants.document.DOC_STATUS["DRAFT"],
                        max_length=20,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rmas",
                        to="sales.customer",
                    ),
                ),
            ],
            options={
                "db_table": "sal_rma",
            },
        ),
        migrations.CreateModel(
            name="RMALine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("qty", models.DecimalField(decimal_places=6, max_digits=20)),
                (
                    "lot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rma_lines",
                        to="inventory.lot",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rma_lines",
                        to="material.material",
                    ),
                ),
                (
                    "rma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="sales.rma",
                    ),
                ),
                (
                    "serial",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rma_lines",
                        to="inventory.serial",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rma_lines",
                        to="material.warehouse",
                    ),
                ),
            ],
            options={
                "db_table": "sal_rma_line",
            },
        ),
        migrations.CreateModel(
            name="SalesOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("doc_no", models.CharField(max_length=64)),
                ("delivery_date", models.DateField(blank=True, null=True)),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=20
                    ),
                ),
                ("special_terms", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (
                                shared.constants.document.DOC_STATUS["DRAFT"],
                                shared.constants.document.DOC_STATUS["DRAFT"],
                            ),
                            (
                                shared.constants.document.DOC_STATUS["SUBMITTED"],
                                shared.constants.document.DOC_STATUS["SUBMITTED"],
                            ),
                            (
                                shared.constants.document.DOC_STATUS["CONFIRMED"],
                                shared.constants.document.DOC_STATUS["CONFIRMED"],
                            ),
                            (
                                shared.constants.document.DOC_STATUS["COMPLETED"],
                                shared.constants.document.DOC_STATUS["COMPLETED"],
                            ),
                            (
                                shared.constants.document.DOC_STATUS["CANCELLED"],
                                shared.constants.document.DOC_STATUS["CANCELLED"],
                            ),
                        ],
                        default=shared.constants.document.DOC_STATUS["DRAFT"],
                        max_length=20,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_orders",
                        to="sales.customer",
                    ),
                ),
            ],
            options={
                "db_table": "sal_sales_order",
                "unique_together": {("company_id", "doc_no")},
            },
        ),
        migrations.AddField(
            model_name="rma",
            name="so",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rmas",
                to="sales.salesorder",
            ),
        ),
        migrations.CreateModel(
            name="SalesOrderLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("qty", models.DecimalField(decimal_places=6, max_digits=20)),
                ("price", models.DecimalField(decimal_places=6, max_digits=20)),
                (
                    "reserved_qty",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_order_lines",
                        to="material.material",
                    ),
                ),
                (
                    "so",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="sales.salesorder",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_order_lines",
                        to="material.warehouse",
                    ),
                ),
            ],
            options={
                "db_table": "sal_sales_order_line",
            },
        ),
        migrations.CreateModel(
            name="SalesQuote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("doc_no", models.CharField(max_length=64)),
                ("valid_until", models.DateField(blank=True, null=True)),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (
                                shared.constants.document.DOC_STATUS["DRAFT"],
                                shared.constants.document.DOC_STATUS["DRAFT"],
                            ),
                            (
                                shared.constants.document.DOC_STATUS["SUBMITTED"],
                                shared.constants.document.DOC_STATUS["SUBMITTED"],
                            ),
                            (
                                shared.constants.document.DOC_STATUS["CONFIRMED"],
                                shared.constants.document.DOC_STATUS["CONFIRMED"],
                            ),
                            (
                                shared.constants.document.DOC_STATUS["COMPLETED"],
                                shared.constants.document.DOC_STATUS["COMPLETED"],
                            ),
                            (
                                shared.constants.document.DOC_STATUS["CANCELLED"],
                                shared.constants.document.DOC_STATUS["CANCELLED"],
                            ),
                        ],
                        default=shared.constants.document.DOC_STATUS["DRAFT"],
                        max_length=20,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_quotes",
                        to="sales.customer",
                    ),
                ),
            ],
            options={
                "db_table": "sal_sales_quote",
                "unique_together": {("company_id", "doc_no")},
            },
        ),
        migrations.CreateModel(
            name="SalesQuoteLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("qty", models.DecimalField(decimal_places=6, max_digits=20)),
                ("price", models.DecimalField(decimal_places=6, max_digits=20)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_quote_lines",
                        to="material.material",
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="sales.salesquote",
                    ),
                ),
            ],
            options={
                "db_table": "sal_sales_quote_line",
            },
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("doc_no", models.CharField(max_length=64)),
                ("ship_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (
                                shared.constants.document.DOC_STATUS["DRAFT"],
                                shared.constants.document.DOC_STATUS["DRAFT"],
                            ),
                            (
                                shared.constants.document.DOC_STATUS["SUBMITTED"],
                                shared.constants.document.DOC_STATUS["SUBMITTED"],
                            ),
                            (
                                shared.constants.document.DOC_STATUS["CONFIRMED"],
                                shared.constants.document.DOC_STATUS["CONFIRMED"],
                            ),
                            (
                                shared.constants.document.DOC_STATUS["COMPLETED"],
                                shared.constants.document.DOC_STATUS["COMPLETED"],
                            ),
                            (
                                shared.constants.document.DOC_STATUS["CANCELLED"],
                                shared.constants.document.DOC_STATUS["CANCELLED"],
                            ),
                        ],
                        default=shared.constants.document.DOC_STATUS["DRAFT"],
                        max_length=20,
                    ),
                ),
                ("carrier", models.CharField(blank=True, max_length=120)),
                ("tracking_no", models.CharField(blank=True, max_length=120)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipments",
                        to="sales.customer",
                    ),
                ),
                (
                    "so",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipments",
                        to="sales.salesorder",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipments",
                        to="material.warehouse",
                    ),
                ),
            ],
            options={
                "db_table": "sal_shipment",
                "unique_together": {("company_id", "doc_no")},
            },
        ),
        migrations.CreateModel(
            name="POD",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("delivered_at", models.DateTimeField()),
                ("receiver_name", models.CharField(max_length=120)),
                ("proof_json", models.JSONField(blank=True, default=dict)),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pods",
                        to="sales.shipment",
                    ),
                ),
            ],
            options={
                "db_table": "sal_pod",
            },
        ),
        migrations.CreateModel(
            name="ShipmentLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("qty", models.DecimalField(decimal_places=6, max_digits=20)),
                (
                    "lot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipment_lines",
                        to="inventory.lot",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipment_lines",
                        to="material.material",
                    ),
                ),
                (
                    "serial",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipment_lines",
                        to="inventory.serial",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="sales.shipment",
                    ),
                ),
                (
                    "so_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipment_lines",
                        to="sales.salesorderline",
                    ),
                ),
            ],
            options={
                "db_table": "sal_shipment_line",
            },
        ),
        migrations.CreateModel(
            name="ShipmentStatusEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("event_code", models.CharField(max_length=64)),
                ("event_time", models.DateTimeField()),
                ("payload_json", models.JSONField(blank=True, default=dict)),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_events",
                        to="sales.shipment",
                    ),
                ),
            ],
            options={
                "db_table": "sal_shipment_status_event",
            },
        ),
        migrations.AlterUniqueTogether(
            name="rma",
            unique_together={("company_id", "doc_no")},
        ),
    ]
